import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Edit3, Plus, Search, ShieldAlert, Trash2, Users, X } from "lucide-react";
import { api } from "../api/client";
import { useDialogDismiss } from "../hooks/useDialogDismiss";
import { useOperationLimit } from "../hooks/useOperationLimit";
import type { TeamCreatePayload, TeamInfo, TeamUpdatePayload } from "../types";
import TeamMembersDialog from "./TeamMembersDialog";

const inputClass = "w-full rounded-lg border border-[#2A2E42] bg-[#0F1117] px-3 py-2 text-sm text-white placeholder-gray-600 focus:border-indigo-500 focus:outline-none";

type EditorState = { mode: "create" } | { mode: "edit"; team: TeamInfo };

function optionalNumber(value: string): number | undefined {
  return value === "" ? undefined : Number(value);
}

function nullableNumber(value: string): number | null {
  return value === "" ? null : Number(value);
}

function TeamEditor({ state, pending, operationsBlocked, error, onClose, onCreate, onUpdate }: {
  state: EditorState;
  pending: boolean;
  operationsBlocked: boolean;
  error?: string;
  onClose: () => void;
  onCreate: (payload: TeamCreatePayload) => void;
  onUpdate: (teamId: string, payload: TeamUpdatePayload) => void;
}) {
  useDialogDismiss(onClose, pending);
  const existing = state.mode === "edit" ? state.team : null;
  const [alias, setAlias] = useState(existing?.team_alias ?? "");
  const [teamId, setTeamId] = useState(existing?.team_id ?? "");
  const [models, setModels] = useState(existing?.models?.join(", ") ?? "");
  const [budget, setBudget] = useState(existing?.max_budget != null ? String(existing.max_budget) : "");
  const [budgetDuration, setBudgetDuration] = useState(existing?.budget_duration ?? "");
  const [tpm, setTpm] = useState(existing?.tpm_limit != null ? String(existing.tpm_limit) : "");
  const [rpm, setRpm] = useState(existing?.rpm_limit != null ? String(existing.rpm_limit) : "");
  const [blocked, setBlocked] = useState(existing?.blocked ?? false);

  function submit(event: React.FormEvent) {
    event.preventDefault();
    const modelList = Array.from(new Set(models.split(/[\n,]/).map(value => value.trim()).filter(Boolean)));
    if (state.mode === "create") {
      const payload: TeamCreatePayload = { team_alias: alias.trim(), models: modelList, blocked };
      if (teamId.trim()) payload.team_id = teamId.trim();
      const maxBudget = optionalNumber(budget);
      const tpmLimit = optionalNumber(tpm);
      const rpmLimit = optionalNumber(rpm);
      if (maxBudget !== undefined) payload.max_budget = maxBudget;
      if (budgetDuration.trim()) payload.budget_duration = budgetDuration.trim();
      if (tpmLimit !== undefined) payload.tpm_limit = tpmLimit;
      if (rpmLimit !== undefined) payload.rpm_limit = rpmLimit;
      onCreate(payload);
      return;
    }
    onUpdate(state.team.team_id, {
      team_alias: alias.trim(),
      models: modelList,
      max_budget: nullableNumber(budget),
      budget_duration: budgetDuration.trim() || null,
      tpm_limit: nullableNumber(tpm),
      rpm_limit: nullableNumber(rpm),
      blocked,
    });
  }

  return (
    <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="team-editor-title" onMouseDown={event => { if (event.target === event.currentTarget && !pending) onClose(); }}>
      <form onSubmit={submit} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-[#2A2E42] bg-[#1A1D27] p-5 shadow-2xl">
        <div className="flex items-start justify-between gap-4">
          <div><h3 id="team-editor-title" className="text-lg font-semibold text-white">{state.mode === "create" ? "Create team" : "Edit team"}</h3><p className="mt-1 text-xs text-gray-500">Models left empty means all models. Blank numeric limits remove the limit when editing.</p></div>
          <button type="button" onClick={onClose} aria-label="Close team editor" className="rounded p-1 text-gray-500 hover:bg-[#22263A] hover:text-white"><X size={18} /></button>
        </div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2">
          <label className="space-y-1 text-xs text-gray-400"><span>Team name</span><input autoFocus className={inputClass} value={alias} onChange={event => setAlias(event.target.value)} maxLength={128} required /></label>
          <label className="space-y-1 text-xs text-gray-400"><span>Team ID {state.mode === "create" && "(optional)"}</span><input className={`${inputClass} font-mono`} value={teamId} onChange={event => setTeamId(event.target.value)} maxLength={128} disabled={state.mode === "edit"} placeholder="Generated by LiteLLM when empty" /></label>
          <label className="space-y-1 text-xs text-gray-400"><span>Maximum budget (USD)</span><input className={inputClass} value={budget} onChange={event => setBudget(event.target.value)} type="number" min="0" step="any" placeholder="Unlimited" /></label>
          <label className="space-y-1 text-xs text-gray-400"><span>Budget reset</span><input className={inputClass} value={budgetDuration} onChange={event => setBudgetDuration(event.target.value)} placeholder="For example 30d" maxLength={32} /></label>
          <label className="space-y-1 text-xs text-gray-400"><span>TPM limit</span><input className={inputClass} value={tpm} onChange={event => setTpm(event.target.value)} type="number" min="0" placeholder="Unlimited" /></label>
          <label className="space-y-1 text-xs text-gray-400"><span>RPM limit</span><input className={inputClass} value={rpm} onChange={event => setRpm(event.target.value)} type="number" min="0" placeholder="Unlimited" /></label>
          <label className="space-y-1 text-xs text-gray-400 sm:col-span-2"><span>Allowed models (comma-separated or one per line)</span><textarea className={`${inputClass} min-h-24`} value={models} onChange={event => setModels(event.target.value)} placeholder="gpt-4o, claude-sonnet" /></label>
          <label className="flex items-center gap-2 text-sm text-gray-300 sm:col-span-2"><input type="checkbox" checked={blocked} onChange={event => setBlocked(event.target.checked)} /> Block requests from this team</label>
        </div>
        {error && <p className="mt-4 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">{error}</p>}
        <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-[#2A2E42] px-4 py-2 text-sm text-gray-300 hover:bg-[#22263A]">Cancel</button><button disabled={pending || operationsBlocked || !alias.trim()} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving..." : operationsBlocked ? "Team actions paused" : state.mode === "create" ? "Create team" : "Save changes"}</button></div>
      </form>
    </div>
  );
}

function DeleteTeamDialog({ team, pending, operationsBlocked, error, onClose, onDelete }: { team: TeamInfo; pending: boolean; operationsBlocked: boolean; error?: string; onClose: () => void; onDelete: () => void }) {
  const [confirmation, setConfirmation] = useState("");
  useDialogDismiss(onClose, pending);
  return <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-team-title" onMouseDown={event => { if (event.target === event.currentTarget && !pending) onClose(); }}>
    <div className="w-full max-w-md rounded-2xl border border-red-500/30 bg-[#1A1D27] p-5 shadow-2xl">
      <div className="flex items-start gap-3"><div className="rounded-lg bg-red-500/10 p-2 text-red-400"><ShieldAlert size={20} /></div><div className="min-w-0 flex-1"><h3 id="delete-team-title" className="font-semibold text-white">Delete {team.team_alias || team.team_id}?</h3><p className="mt-1 text-xs leading-5 text-gray-400">LiteLLM deletes this team and its team-scoped API keys. This cannot be undone by LiteGate.</p></div><button onClick={onClose} aria-label="Close delete dialog" className="text-gray-500 hover:text-white"><X size={18} /></button></div>
      <label className="mt-4 block space-y-1 text-xs text-gray-400"><span>Type <code className="text-red-300">{team.team_id}</code> to confirm</span><input autoFocus className={inputClass} value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label>
      {error && <p className="mt-3 text-xs text-red-300">{error}</p>}
      <div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border border-[#2A2E42] px-4 py-2 text-sm text-gray-300">Cancel</button><button onClick={onDelete} disabled={pending || operationsBlocked || confirmation !== team.team_id} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-500 disabled:cursor-not-allowed disabled:opacity-40">{pending ? "Deleting..." : operationsBlocked ? "Team actions paused" : "Delete team and keys"}</button></div>
    </div>
  </div>;
}

export default function AdminTeams() {
  const queryClient = useQueryClient();
  const { operationsBlocked, retryAfter, refreshOperationLimit } = useOperationLimit();
  const [page, setPage] = useState(1);
  const [searchInput, setSearchInput] = useState("");
  const [search, setSearch] = useState("");
  const [editor, setEditor] = useState<EditorState | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<TeamInfo | null>(null);
  const [memberTeam, setMemberTeam] = useState<TeamInfo | null>(null);

  const teams = useQuery({ queryKey: ["teams", page, search], queryFn: () => api.listTeams(page, 25, search), placeholderData: previous => previous });
  const create = useMutation({ mutationFn: api.createTeam, onSuccess: () => { setEditor(null); void queryClient.invalidateQueries({ queryKey: ["teams"] }); }, onSettled: refreshOperationLimit });
  const update = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: TeamUpdatePayload }) => api.updateTeam(id, payload), onSuccess: () => { setEditor(null); void queryClient.invalidateQueries({ queryKey: ["teams"] }); void queryClient.invalidateQueries({ queryKey: ["keys"] }); }, onSettled: refreshOperationLimit });
  const remove = useMutation({ mutationFn: api.deleteTeam, onSuccess: () => { setDeleteTarget(null); void queryClient.invalidateQueries({ queryKey: ["teams"] }); void queryClient.invalidateQueries({ queryKey: ["keys"] }); }, onSettled: refreshOperationLimit });
  const moveMember = useMutation({ mutationFn: ({ sourceTeamId, userId, destinationTeamId }: { sourceTeamId: string; userId: string; destinationTeamId: string }) => api.moveTeamMember(sourceTeamId, { user_id: userId, destination_team_id: destinationTeamId, confirm_policy_change: true }), onSuccess: () => { setMemberTeam(null); void queryClient.invalidateQueries({ queryKey: ["teams"] }); void queryClient.invalidateQueries({ queryKey: ["keys"] }); }, onSettled: refreshOperationLimit });

  function applySearch(event: React.FormEvent) { event.preventDefault(); setPage(1); setSearch(searchInput.trim()); }
  function openCreate() { create.reset(); update.reset(); setEditor({ mode: "create" }); }
  function openEdit(team: TeamInfo) { create.reset(); update.reset(); setEditor({ mode: "edit", team }); }
  function openDelete(team: TeamInfo) { remove.reset(); setDeleteTarget(team); }
  function openMembers(team: TeamInfo) { moveMember.reset(); setMemberTeam(team); }

  const pageCount = Math.max(1, teams.data?.total_pages ?? 1);
  const pageError = teams.error as Error | null;
  const editorError = (editor?.mode === "create" ? create.error : update.error) as Error | null;

  return <section className="w-full max-w-5xl space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-medium uppercase tracking-wider text-cyan-400">Teams</p><h2 className="mt-1 text-xl font-semibold text-white">LiteLLM team policy</h2><p className="mt-1 text-sm text-gray-500">Manage team budgets, model access, rate limits, and availability without opening the LiteLLM admin UI.</p></div><button onClick={openCreate} disabled={operationsBlocked} className="flex items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-40"><Plus size={16} /> {operationsBlocked ? "Team actions paused" : "Create team"}</button></div>

    <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3 text-xs leading-5 text-amber-100/70"><span className="font-medium text-amber-200">Deletion is intentionally guarded.</span> Deleting a LiteLLM team also deletes its team-scoped keys. Teams referenced by SSO mapping or <code>KEY_TEAM_ID</code> cannot be deleted until that configuration is changed.</div>
    {operationsBlocked && <p className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">Team actions are paused. Try again in {retryAfter || 1} seconds.</p>}

    <form onSubmit={applySearch} className="flex gap-2"><div className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-600" /><input aria-label="Search teams" className={`${inputClass} pl-9`} value={searchInput} onChange={event => setSearchInput(event.target.value)} placeholder="Search team name or ID" maxLength={128} /></div><button className="rounded-lg border border-[#2A2E42] px-4 py-2 text-sm text-gray-300 hover:bg-[#1A1D27]">Search</button></form>

    {pageError && <p className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{pageError.message}</p>}
    <div className="overflow-hidden rounded-xl border border-[#2A2E42] bg-[#1A1D27]">
      <div className="flex items-center justify-between border-b border-[#2A2E42] px-4 py-3"><span className="text-sm font-medium text-gray-200">{teams.data?.total ?? 0} teams</span>{teams.isFetching && <span className="text-xs text-gray-600">Refreshing...</span>}</div>
      {teams.isLoading ? <div className="h-48 animate-pulse bg-[#22263A]" /> : teams.data?.teams.length ? <div className="divide-y divide-[#2A2E42]">{teams.data.teams.map(team => {
        const protectedTeam = team.mapped_groups.length > 0 || team.default_key_team;
        return <article key={team.team_id} className="p-4">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-center">
            <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Building2 size={16} className="text-cyan-400" /><h3 className="truncate text-sm font-semibold text-white">{team.team_alias || "Unnamed team"}</h3>{team.blocked && <span className="rounded bg-red-500/15 px-1.5 py-0.5 text-[10px] text-red-300">Blocked</span>}{team.default_key_team && <span className="rounded bg-indigo-500/15 px-1.5 py-0.5 text-[10px] text-indigo-300">Default key team</span>}{team.mapped_groups.map(group => <span key={group} className="rounded bg-cyan-500/10 px-1.5 py-0.5 text-[10px] text-cyan-300">SSO: {group}</span>)}</div><p className="mt-1 truncate font-mono text-[11px] text-gray-600" title={team.team_id}>{team.team_id}</p></div>
            <div className="grid grid-cols-3 gap-4 text-xs lg:min-w-80"><div><p className="text-gray-600">Budget</p><p className="mt-0.5 text-gray-300">{team.max_budget != null ? `$${team.max_budget}` : "Unlimited"}</p></div><div><p className="text-gray-600">Usage</p><p className="mt-0.5 text-gray-300">${(team.spend ?? 0).toFixed(2)}</p></div><div><p className="text-gray-600">Members / keys</p><p className="mt-0.5 text-gray-300">{team.members_count ?? 0} / {team.keys_count ?? 0}</p></div><div><p className="text-gray-600">Models</p><p className="mt-0.5 text-gray-300">{team.models?.length ? team.models.length : "All"}</p></div><div><p className="text-gray-600">TPM</p><p className="mt-0.5 text-gray-300">{team.tpm_limit?.toLocaleString() ?? "Default"}</p></div><div><p className="text-gray-600">RPM</p><p className="mt-0.5 text-gray-300">{team.rpm_limit?.toLocaleString() ?? "Default"}</p></div></div>
            <div className="flex flex-wrap gap-2"><button onClick={() => openMembers(team)} disabled={operationsBlocked} className="flex items-center gap-1.5 rounded-lg border border-cyan-500/20 px-3 py-2 text-xs text-cyan-300 hover:bg-cyan-500/10 disabled:cursor-not-allowed disabled:opacity-35"><Users size={13} /> Members</button><button onClick={() => openEdit(team)} disabled={operationsBlocked} className="flex items-center gap-1.5 rounded-lg border border-[#2A2E42] px-3 py-2 text-xs text-gray-300 hover:bg-[#22263A] disabled:cursor-not-allowed disabled:opacity-35"><Edit3 size={13} /> Edit</button><button onClick={() => openDelete(team)} disabled={protectedTeam || operationsBlocked} title={protectedTeam ? "Remove SSO/default-team configuration references first" : operationsBlocked ? "Wait for the operation cooldown" : "Delete team"} className="flex items-center gap-1.5 rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-300 hover:bg-red-500/10 disabled:cursor-not-allowed disabled:opacity-35"><Trash2 size={13} /> Delete</button></div>
          </div>
        </article>;
      })}</div> : <p className="p-10 text-center text-sm text-gray-500">{search ? "No teams match this search." : "No LiteLLM teams yet. Create the first team to define a shared budget and model policy."}</p>}
      <div className="flex items-center justify-between border-t border-[#2A2E42] px-4 py-3 text-xs"><button onClick={() => setPage(value => Math.max(1, value - 1))} disabled={page <= 1} className="text-gray-400 disabled:opacity-30">Previous</button><span className="text-gray-600">Page {page} of {pageCount}</span><button onClick={() => setPage(value => Math.min(pageCount, value + 1))} disabled={page >= pageCount} className="text-gray-400 disabled:opacity-30">Next</button></div>
    </div>

    {editor && <TeamEditor key={editor.mode === "edit" ? editor.team.team_id : "create"} state={editor} pending={create.isPending || update.isPending} operationsBlocked={operationsBlocked} error={editorError?.message} onClose={() => setEditor(null)} onCreate={payload => create.mutate(payload)} onUpdate={(id, payload) => update.mutate({ id, payload })} />}
    {deleteTarget && <DeleteTeamDialog team={deleteTarget} pending={remove.isPending} operationsBlocked={operationsBlocked} error={(remove.error as Error | null)?.message} onClose={() => setDeleteTarget(null)} onDelete={() => remove.mutate(deleteTarget.team_id)} />}
    {memberTeam && <TeamMembersDialog team={memberTeam} pending={moveMember.isPending} operationsBlocked={operationsBlocked} error={(moveMember.error as Error | null)?.message} onClose={() => setMemberTeam(null)} onMove={(userId, destinationTeamId) => moveMember.mutate({ sourceTeamId: memberTeam.team_id, userId, destinationTeamId })} />}
  </section>;
}
